workflows:
  build-ios:
    name: Build iOS .ipa
    environment:
      flutter: stable
      xcode: latest
    working_directory: flutter_application_1
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS release (no code signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
